### ISSUE TITLE
TIL 레포지토리를 체계적으로 관리해보기

### ISSUE THREAD

**Issue by l0vey0u** [l0vey0u/ToDo#25]
[milooy님의 TIL페이지](http://milooy.github.io/TIL/) 를 보면 내가 원하는
TIL이 블로그가 되는 느낌이다.
물론 저 페이지는 일종의 Wiki 느낌이지만 커스터 마이징에 따라 달라질 사항이니..

[TIL레포](https://github.com/milooy/TIL)를 보면 
[외국개발자의 레포](https://github.com/thoughtbot/til)를 참고 한 것 같은데
한번 적용해봐야 겠다.

**Comment by l0vey0u** [comment]
내 추측은 일부 빗나갔다.
[vuepress](https://limdongjin.github.io/vuejs/vuepress/)라는 것을 사용하고 있었다.

**Comment by l0vey0u** [comment]
[뷰프레스튜토리얼](https://limdongjin.github.io/vuejs/vuepress/#%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8-%EC%84%A4%EC%B9%98-%EB%B0%8F-%EB%B9%8C%EB%93%9C)

[캡틴판교_vuepress가이드](https://joshua1988.github.io/vue-camp/vuepress/learning-note.html#%EC%82%AC%EC%9D%B4%ED%8A%B8-%EB%B0%B0%ED%8F%AC-%ED%95%98%EA%B8%B0-%EC%A0%88%EC%B0%A8)

이 두 글을 참고하여 만들어 보고 있는데
master:gh-pages 이게 l0vey0u.github.io를 따로 만들지 않아도?
l0vey0u.github.io에 자동 등록? 되게 하고 있는거 같은데 알아봐야 겠다.

**Comment by l0vey0u** [comment]
아 내가 잘못 알고 있던 것이 있었다.
[github blog 페이지에 대하여](https://mygumi.tistory.com/285)
이 글을 보니 원래 되는 거구나..

**Comment by l0vey0u** [comment]
그래서 dev 랑 build 차이 먼지도 알아서 TIL에 기록하자

**Comment by l0vey0u** [comment]
https://github.com/ulivz/vuepress-blog-example-egoist

**Comment by l0vey0u** [comment]
https://ake.kr/2018/12/31/static-page-site-management-in-github-pages/#jekyll-first%EC%9D%98-github-pages

나처럼 가벼운 유저들에겐 해당 사항이 아니지만
Traffic 100GB /m, Max 1GB 는 좀 중반급 블로그만 되도
상당한 제약이 될 것 같다.

그리고 GithubPages가 jekyll에 맞혀져 있어서
VuePress같이 다른 정적 프레임워크를 쓰려면 .nojekyll을 root에 두어야 한다고..

**Comment by l0vey0u** [comment]
- https://unhosted.tistory.com/21

- https://choibu.github.io/TIL/#deploy

- https://github.com/ChoiBU/TIL/blob/master/all.sh

@choibu 님 TIL 페이지가 내가 원하는 방향과 비슷한 것 같아서 참고해봄

**Comment by l0vey0u** [comment]
ChoiBU님 TIL 페이지 참고한 결과 만족스러워 졌다.
댓글 기능은 아직 내가 필요없다고 생각되서 추가 안하고 있다. ㅋㅋ

**Comment by ByeongUkChoi** [comment]
헉 대단한것은 아니지만 참고한 결과가 만족스러워 졌다고 하시니 되려 감사합니다.
이미 지난 글이지만 계정 명을 변경해 주소가 바뀌었습니다.
https://ByeongUkChoi.github.io/TIL/#deploy
https://github.com/ByeongUkChoi/TIL/blob/master/all.sh
블로그 보고 많이 배우고 갑니다. 감사합니다!
